services:
  backend:
    build: .
    container_name: be_scada_api
    ports:
      - "5959:5959"
    env_file: .env
    depends_on:
      - db
    restart: on-failure 

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: scada
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5960"

volumes:
  pg-data:
